services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PW}
        - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
        ports:
        - "5432:5432"
        restart: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
        ports:
        - "5050:80"
        restart: always

    ollama:
        image: ollama/ollama:0.1.44
        ports:
        - "11434:11434"
        volumes:
        - ollama-local:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
        - ./Modelfile:/Modelfile
        - /Users/vlemordant/llm/mlx-examples/lora/lora_fused_model:/shared
        entrypoint: ["sh", "./entrypoint.sh"]

    openWebUI:
        build:
            context: .
            args:
                OLLAMA_BASE_URL: '/ollama'
            dockerfile: Dockerfile
        image: ghcr.io/open-webui/open-webui:main
        container_name: ollama-webui
        depends_on:
        - ollama
        restart: always
        ports:
        - "3000:8080"
        environment:
        - "OLLAMA_BASE_URL=http://ollama:11434"
        extra_hosts:
        - "host.docker.internal:host-gateway"
        volumes:
        - open-webui-local:/app/backend/data

volumes:
    ollama-local:
        external: false
    open-webui-local:
        external: false